# Generated by Django 5.2 on 2026-01-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_product_author_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
